baseURL: https://yangzh313.github.io/
languageCode: 
  - en-us
  - zh
title: PeaceKeeper
theme: "papermod"
paginate: 3
author:
  name: "Jacob Zhao"
  url: "https://github.com/yangzh313"
  avatar: "avatar.png"

params:
  homeInfoParams:
    Title: Hi you
    Content: Peace of mind.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/yangzh313"
  ShowReadingTime: true
  author: "Jacob"
  contact: "yangzh24@outlook.com"
  feedlinks: true
  # footer: "Powered by [Hugo](https://gohugo.io/) and the [Logseq](https://logseq.com/)."
  # copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  canonifyURLs: true
  # favicon: "favicon.ico"
  # icon: "unicorn.ico"
  # image: "unicorn.ico"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20